import './shared-header.js';
import { authenticatedRequest, currentSession } from './auth.js';

const actionStylesheet = document.querySelector('link[href="styles.css"]'); if (actionStylesheet) actionStylesheet.href = 'styles.css?v=action-plans-10-5';

const $ = (id) => document.getElementById(id); const form = $('action-form'); let editingId = null; let plans = [];
const profileContext = new URLSearchParams(location.search);
const ownerInput = form.querySelector('[name="owner_team"]'); const ownerLabel = ownerInput?.closest('label'); const ownerOptions = ['HR', 'Administration', 'Counselor', 'School Leadership', 'Attendance Team', 'Graduation / College Counseling', 'Student Support', 'Data / Inquiry Team', 'Other']; const ownerSelect = document.createElement('select'); ownerSelect.name = 'owner_team'; ownerSelect.required = true; ownerSelect.append(new Option('Select owner team', '')); ownerOptions.forEach((value) => { const option = document.createElement('option'); option.value = value; option.textContent = value; ownerSelect.append(option); }); ownerSelect.value = ''; const otherOwner = document.createElement('input'); otherOwner.name = 'other_owner_team'; otherOwner.placeholder = 'Specify other owner team'; otherOwner.hidden = true; if (ownerLabel) { ownerInput.replaceWith(ownerSelect, otherOwner); }
const escalationLabel = document.createElement('label'); escalationLabel.textContent = 'Escalation level'; const escalationSelect = document.createElement('select'); escalationSelect.name = 'escalation_level'; [['', 'No escalation'], ['Principal', 'Principal'], ['Assistant Principal', 'Assistant Principal'], ['Superintendent’s Office', 'Superintendent’s Office'], ['Senior District Leadership', 'Senior District Leadership'], ['DOE Liaison', 'DOE Liaison'], ['Other', 'Other']].forEach(([value, label]) => { const option = document.createElement('option'); option.value = value; option.textContent = label; escalationSelect.append(option); }); escalationLabel.append(escalationSelect); form.querySelector('[name="status"]')?.closest('label')?.before(escalationLabel);
const years = form.querySelector('[name="school_year"]'); const dbnField = form.querySelector('[name="dbn"]'); const dateField = form.querySelector('[name="follow_up_date"]'); const demographicField = form.querySelector('[name="demographic"]'); const dateMessageElement = document.createElement('p'); dateMessageElement.className = 'field-error'; dateMessageElement.id = 'follow-up-date-error'; dateMessageElement.setAttribute('aria-live', 'polite'); dateField.after(dateMessageElement); const dbnMessageElement = document.createElement('p'); dbnMessageElement.className = 'field-error'; dbnMessageElement.id = 'dbn-error'; dbnMessageElement.setAttribute('aria-live', 'polite'); dbnField.after(dbnMessageElement); const demographics = new Set([...demographicField.options].map((option) => option.value)); let supportedYears = new Set(); let optionsError = false; let dbnExists = false; let dbnSearchTimer = null; let dbnSearchController = null; let dbnSearchSequence = 0;
const nativeDbnList = document.getElementById('dbn-options'); nativeDbnList?.remove(); const dbnResults = document.createElement('div'); dbnResults.id = 'dbn-results'; dbnResults.className = 'dbn-results'; dbnResults.style.cssText = 'position:absolute;left:0;right:0;top:100%;z-index:20;max-height:260px;overflow-y:auto;background:#fff;border:1px solid #dbe3ee;border-radius:4px;box-shadow:0 8px 18px #17203322;'; dbnResults.setAttribute('role', 'listbox'); dbnResults.setAttribute('aria-label', 'DBN search results'); dbnResults.hidden = true; dbnField.closest('label')?.classList.add('dbn-field'); dbnField.after(dbnResults);
const today = new Date(); const dateIso = (date) => new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate())).toISOString().slice(0, 10); const minFollowUp = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 1); const maxFollowUp = new Date(today.getFullYear(), today.getMonth(), today.getDate() + 30); dateField.min = dateIso(minFollowUp); dateField.max = dateIso(maxFollowUp);
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
function dateError(value) { if (!value) return ''; const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value); if (!match) return 'Use the date format YYYY-MM-DD.'; const year = Number(match[1]); const month = Number(match[2]); const day = Number(match[3]); const daysInMonth = new Date(Date.UTC(year, month, 0)).getUTCDate(); const today = new Date(); const todayUtc = new Date(Date.UTC(today.getFullYear(), today.getMonth(), today.getDate())); const minDate = new Date(todayUtc); minDate.setUTCDate(minDate.getUTCDate() + 1); const maxDate = new Date(todayUtc); maxDate.setUTCDate(maxDate.getUTCDate() + 30); const parsed = new Date(Date.UTC(year, month - 1, day)); const iso = parsed.toISOString().slice(0, 10); if (month < 1 || month > 12 || day < 1 || day > daysInMonth || iso !== value) return 'Enter a real calendar date for the selected month and year.'; if (parsed < minDate || parsed > maxDate) return 'Choose a follow-up date from tomorrow through 30 days from today.'; return ''; }
function dbnError(value) { if (!value || !/^\d{2}[A-Z]\d{3}$/i.test(value)) return ''; return /^[0-9]{2}[MXKQR][0-9]{3}$/i.test(value) ? '' : 'Use two numbers, M/X/K/Q/R, then three numbers (example: 01M292).'; }
function requiredReady() { const dbnMessage = dbnError(dbnField.value); const schoolMessage = dbnField.value.trim() && !dbnExists ? 'Select a school from the search results.' : ''; const dateMessage = dateError(dateField.value); dateField.setCustomValidity(dateMessage); dateField.setAttribute('aria-invalid', dateMessage ? 'true' : 'false'); dateMessageElement.textContent = dateMessage; dateMessageElement.hidden = !dateMessage; dbnField.setCustomValidity(dbnMessage || schoolMessage); dbnField.setAttribute('aria-invalid', dbnMessage || schoolMessage ? 'true' : 'false'); dbnMessageElement.textContent = dbnMessage || schoolMessage; dbnMessageElement.hidden = !(dbnMessage || schoolMessage); }
function resetForm() { editingId = null; form.reset(); $('form-title').textContent = 'New action plan'; $('save-action').textContent = 'Save action plan'; $('cancel-edit').hidden = true; requiredReady(); }
function render() { const ownerFilter = $('plan-owner-filter')?.value || ''; const dbnFilter = $('plan-dbn-filter')?.value || ''; const owners = [...new Set(plans.map((plan) => plan.owner_team).filter(Boolean))].sort(); const dbns = [...new Set(plans.map((plan) => plan.dbn).filter(Boolean))].sort(); const rebuildFilter = (id, values, allLabel) => { const select = $(id); if (!select) return; const selected = select.value; select.replaceChildren(new Option(allLabel, ''), ...values.map((value) => new Option(value, value))); select.value = values.includes(selected) ? selected : ''; }; rebuildFilter('plan-owner-filter', owners, 'All owner teams'); rebuildFilter('plan-dbn-filter', dbns, 'All schools'); const visiblePlans = plans.filter((plan) => (!ownerFilter || plan.owner_team === ownerFilter) && (!dbnFilter || plan.dbn === dbnFilter)); $('action-count').textContent = `${visiblePlans.length} of ${plans.length} plan${plans.length === 1 ? '' : 's'}`; $('action-list').innerHTML = visiblePlans.map((plan) => `<article class="action-item"><div><h4>${escapeHtml(plan.dbn)} · ${escapeHtml(plan.school_name || plan.schoolName || 'School name unavailable')}</h4><p>${escapeHtml(plan.demographic)} · ${escapeHtml(plan.owner_team)} · Escalation: ${escapeHtml(plan.escalation_level || 'None')} · ${escapeHtml(plan.status)}</p></div><div class="plan-actions"><button class="view-plan" data-id="${escapeHtml(plan.id)}" type="button">View / edit</button><button class="delete-plan" data-id="${escapeHtml(plan.id)}" type="button">Delete plan</button></div></article>`).join('') || '<p class="empty">No Action Plans match the selected filters.</p>'; document.querySelectorAll('.view-plan').forEach((button) => button.onclick = () => editPlan(plans.find((plan) => plan.id === button.dataset.id))); document.querySelectorAll('.delete-plan').forEach((button) => button.onclick = () => deletePlan(button.dataset.id)); }
function addOption(select, label, value) { const option = document.createElement('option'); option.textContent = label; option.value = value; select.appendChild(option); }
async function loadOptions() { $('action-status').textContent = 'Loading supported school years and schools…'; try { const metadata = await fetch('/api/portfolio_meta?source=action-plans', { cache: 'no-store' }); if (!metadata.ok) throw Error('School year options are unavailable.'); const data = await metadata.json(); if (!Array.isArray(data.years) || !data.years.length) throw Error('No supported school years were returned.'); years.parentElement.firstChild.textContent = 'Evidence school year'; years.replaceChildren(); addOption(years, 'Select school year', ''); data.years.forEach((year) => { supportedYears.add(String(year)); addOption(years, year, year); }); years.value = String(data.years[data.years.length - 1]); optionsError = false; $('action-status').textContent = 'School years loaded.'; } catch (error) { optionsError = true; years.replaceChildren(); addOption(years, 'School years unavailable', ''); $('action-status').textContent = error.message; } requiredReady(); }
function applyProfileContext() { const contextDbn = profileContext.get('dbn'); const contextYear = profileContext.get('school_year'); const contextDemographic = profileContext.get('demographic'); if (!contextDbn || !contextYear) return; dbnField.value = contextDbn.toUpperCase(); if (supportedYears.has(contextYear)) years.value = contextYear; if (contextDemographic && demographics.has(contextDemographic)) demographicField.value = contextDemographic; checkDbn(); }
async function checkDbn() { const value = dbnField.value; const sequence = ++dbnSearchSequence; if (dbnSearchController) dbnSearchController.abort(); if (!value || dbnError(value)) { dbnExists = false; dbnResults.replaceChildren(); dbnResults.hidden = true; requiredReady(); return; } dbnSearchController = new AbortController(); dbnMessageElement.textContent = 'Checking DBN…'; dbnMessageElement.hidden = false; try { const response = await fetch(`/api/portfolio?limit=100&dbn_prefix=${encodeURIComponent(value)}`, { signal: dbnSearchController.signal }); if (!response.ok) throw Error('Unable to search this DBN.'); const result = await response.json(); if (sequence !== dbnSearchSequence) return; const matches = Array.isArray(result.schools) ? result.schools : []; const uniqueMatches = [...new Map(matches.map((school) => [school.dbn, school])).values()]; dbnResults.replaceChildren(); uniqueMatches.slice(0, 10).forEach((school) => { const option = document.createElement('button'); option.type = 'button'; option.className = 'dbn-result'; option.style.cssText = 'display:grid;width:100%;gap:2px;padding:9px 10px;border:0;border-bottom:1px solid #dbe3ee;background:#fff;color:#172033;text-align:left;cursor:pointer;appearance:none;-webkit-appearance:none;'; option.setAttribute('role', 'option'); option.innerHTML = `<strong>${escapeHtml(school.dbn)}</strong><span style="color:#64748b;font-size:12px">${escapeHtml(school.schoolName || 'School name unavailable')} · ${escapeHtml(school.borough || '')}</span>`; option.addEventListener('click', () => { dbnField.value = school.dbn; dbnExists = true; dbnResults.hidden = true; requiredReady(); }); dbnResults.append(option); }); dbnResults.hidden = false; dbnMessageElement.textContent = uniqueMatches.length ? `${uniqueMatches.length} matching school${uniqueMatches.length === 1 ? '' : 's'} found; showing up to 10.` : 'No valid results found. Please refine your search or look up the directory from the Schools tab.'; if (!uniqueMatches.length) dbnResults.innerHTML = '<p class="dbn-no-results">No valid results found. Please refine your search or look up the directory from the Schools tab.</p>'; dbnExists = value.length === 6 && uniqueMatches.some((school) => school.dbn === value); } catch (error) { if (error.name === 'AbortError') return; dbnExists = false; dbnResults.hidden = false; dbnResults.innerHTML = `<p class="dbn-no-results">${escapeHtml(error.message)}</p>`; dbnMessageElement.textContent = error.message; } requiredReady(); }
async function loadPlans() { if (!currentSession()?.access_token) { window.location.replace('login.html'); return; } try { plans = await authenticatedRequest('action_plans?select=*&order=updated_at.desc') || []; const dbns = [...new Set(plans.map((plan) => plan.dbn).filter(Boolean))]; if (dbns.length) { const directoryResults = await Promise.all(dbns.map(async (dbn) => { const response = await fetch(`/api/portfolio?directory=latest&limit=100&dbn=${encodeURIComponent(dbn)}`); return response.ok ? response.json() : { schools: [] }; })); const schools = new Map(directoryResults.flatMap((result) => result.schools || []).map((school) => [school.dbn, school.schoolName])); plans = plans.map((plan) => ({ ...plan, school_name: schools.get(plan.dbn) || plan.school_name })); } render(); if (!optionsError) $('action-status').textContent = 'Signed in; Action Plans are protected by Supabase Auth and RLS.'; } catch (error) { $('action-status').textContent = error.message; $('action-list').innerHTML = '<p class="empty">Unable to load Action Plans. Check your session or try again.</p>'; } }
function editPlan(plan) { if (!plan) return; editingId = plan.id; dbnField.value = plan.dbn; years.value = plan.school_year; demographicField.value = demographics.has(plan.demographic) ? plan.demographic : ''; form.querySelector('[name="recommended_review"]').value = plan.recommended_review; ownerSelect.value = ownerOptions.includes(plan.owner_team) ? plan.owner_team : 'Other'; otherOwner.value = ownerOptions.includes(plan.owner_team) ? '' : (plan.owner_team || ''); otherOwner.hidden = ownerSelect.value !== 'Other'; escalationSelect.value = plan.escalation_level || ''; form.querySelector('[name="status"]').value = plan.status; dateField.value = plan.follow_up_date || ''; form.querySelector('[name="notes"]').value = plan.notes || ''; form.querySelectorAll('[name="selected_actions"]').forEach((box) => { box.checked = (plan.selected_actions || []).includes(box.value); }); $('form-title').textContent = 'Edit action plan'; $('save-action').textContent = 'Save changes'; $('cancel-edit').hidden = false; requiredReady(); form.scrollIntoView({ behavior: 'smooth', block: 'start' }); }
form.addEventListener('input', (event) => { if (event.target === dbnField) { const raw = dbnField.value.toUpperCase(); const allowed = [...raw].filter((character, index) => index < 2 ? /[0-9]/.test(character) : index === 2 ? /[MXKQR]/.test(character) : /[0-9]/.test(character)).slice(0, 6).join(''); dbnField.value = allowed; dbnExists = false; clearTimeout(dbnSearchTimer); dbnSearchTimer = setTimeout(checkDbn, 250); } requiredReady(); }); form.addEventListener('change', (event) => { if (event.target.name === 'review_template') form.querySelector('[name="recommended_review"]').value = event.target.value === 'custom' ? '' : event.target.value; if (event.target === ownerSelect) { otherOwner.hidden = ownerSelect.value !== 'Other'; otherOwner.required = ownerSelect.value === 'Other'; } requiredReady(); }); dateField.addEventListener('blur', () => { const message = dateError(dateField.value); dateField.setCustomValidity(message); dateField.title = message; }); $('cancel-edit').onclick = resetForm;
form.addEventListener('submit', async (event) => { event.preventDefault(); requiredReady(); if ($('save-action').disabled) return; const session = currentSession(); const data = new FormData(form); const selectedOwner = data.get('owner_team') === 'Other' ? data.get('other_owner_team').trim() : data.get('owner_team'); const payload = { dbn: data.get('dbn'), school_year: Number(data.get('school_year')), demographic: data.get('demographic'), recommended_review: data.get('recommended_review'), owner_team: selectedOwner, escalation_level: data.get('escalation_level') || null, status: data.get('status'), selected_actions: data.getAll('selected_actions'), follow_up_date: data.get('follow_up_date') || null, notes: data.get('notes') || null }; $('action-status').textContent = editingId ? 'Saving changes…' : 'Saving action plan…'; try { if (!session?.user?.id) throw Error('Please sign in to continue.'); if (editingId) await authenticatedRequest(`action_plans?id=eq.${encodeURIComponent(editingId)}`, { method: 'PATCH', headers: { Prefer: 'return=minimal' }, body: JSON.stringify(payload) }); else await authenticatedRequest('action_plans', { method: 'POST', headers: { Prefer: 'return=minimal' }, body: JSON.stringify({ ...payload, created_by: session.user.id }) }); resetForm(); $('action-status').textContent = 'Action Plan saved.'; await loadPlans(); } catch (error) { $('action-status').textContent = error.message; } });
loadOptions().then(applyProfileContext).finally(loadPlans);

$('plan-owner-filter')?.addEventListener('change', render);
$('plan-dbn-filter')?.addEventListener('change', render);

// Phase 10.5 interaction refinements: keep the persisted DBN separate from the
// free-text school search, and validate on Save so users can reach the first gap.
const schoolSearch = document.createElement('input');
schoolSearch.type = 'search'; schoolSearch.placeholder = '01M292 or school name'; schoolSearch.setAttribute('aria-label', 'Search school by DBN or name');
dbnField.hidden = true; dbnField.required = true; dbnField.before(schoolSearch);
let schoolSearchTimer = null;
schoolSearch.addEventListener('input', () => { dbnExists = false; dbnField.value = ''; clearTimeout(schoolSearchTimer); schoolSearchTimer = setTimeout(async () => { const value = schoolSearch.value.trim(); if (!value) { dbnResults.hidden = true; requiredReady(); return; } const key = /^\d{2}[A-Z]\d{0,3}$/i.test(value) ? (value.length === 6 ? 'dbn' : 'dbn_prefix') : 'school_name'; try { const response = await fetch(`/api/portfolio?directory=latest&limit=100&${key}=${encodeURIComponent(value)}`); const result = await response.json(); const matches = [...new Map((result.schools || []).map((school) => [school.dbn, school])).values()].slice(0, 10); dbnResults.replaceChildren(); matches.forEach((school) => { const option = document.createElement('button'); option.type = 'button'; option.className = 'dbn-result'; option.textContent = `${school.dbn} · ${school.schoolName || 'School name unavailable'} · ${school.borough || ''}`; option.onclick = () => { dbnField.value = school.dbn; schoolSearch.value = `${school.dbn} · ${school.schoolName || ''}`; dbnExists = true; dbnResults.hidden = true; requiredReady(); }; dbnResults.append(option); }); dbnResults.hidden = false; dbnMessageElement.textContent = matches.length ? 'Select a school from the results.' : 'No matching school found.'; } catch (error) { dbnMessageElement.textContent = error.message; } requiredReady(); }, 250); });
form.addEventListener('submit', (event) => { requiredReady(); const invalid = form.querySelector(':invalid'); if (!form.reportValidity()) { event.preventDefault(); (invalid === dbnField ? schoolSearch : invalid)?.focus(); return; } if (!form.querySelector('[name="selected_actions"]:checked')) { event.preventDefault(); $('action-status').textContent = 'Select at least one action before saving.'; form.querySelector('[name="selected_actions"]')?.focus(); } }, true);

async function deletePlan(id) { const plan = plans.find((item) => item.id === id); if (!plan || !window.confirm(`Delete Action Plan for ${plan.dbn} · ${plan.school_year}?`)) return; try { await authenticatedRequest(`action_plans?id=eq.${encodeURIComponent(id)}`, { method: 'DELETE', headers: { Prefer: 'return=minimal' } }); if (editingId === id) resetForm(); $('action-status').textContent = 'Action Plan deleted.'; await loadPlans(); } catch (error) { $('action-status').textContent = error.message; } }
